prompt = "a woman standing in the plain"
count = 0
openpose = false
positive = "photorealistic, raw photo, realistic detailed skin, skin pores, natural lighting, sharp focus, 85mm photograph, natural color, detailed face, clear symmetric eyes, detailed hands with five fingers, natural hand pose, anatomically correct body, natural body proportions"
negative = "synthesis body, lowres, bad anatomy, worst quality, extra hand, not 5-fingers, malformed body, diffrent faces upper body and under body, malformed feet, extra feet, missing feet, deformed limbs, duplicate, clone, repeated, collage, panels, grid, tiling, seamless pattern, complementary colors, duotone, two-tone, color grading, oversaturated, don't water come out of hands, don't water come out of dildos."
cfg = 1.0
steps = 30
seed = "-1"
width = 1024
height = 1024
sampler = "dpmpp_2m"
scheduler = "karras"
lora_total = 0.8
adetailer = true
hires_fix = true
hires_scale = 1.5
hires_denoise = 0.35
hires_steps = 20
adetailer_person = false
checkpoint_random = true
lora_keywords = ""
arch_filter = "real"
auto_upscale = true
auto_upscale_style = "real"
many = true
prompt_mode = "toml"
guidance = 3.5
